run_name: ${iteration}
output_dir: ${iteration}
model_name_or_path: ${model_path}
ref_model: ${initial_model}
learning_rate: 5e-7
num_train_epochs: 2
logging_steps: 1
gradient_checkpointing: true
do_train: true
do_eval: true
eval_steps: 100
choose_type: max_min
train_dir: ${model_output}
eval_dir: ${model_output}
loss_type: sigmoid
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1000
eval_strategy: steps
bf16: true
per_device_train_batch_size: 1
per_device_eval_batch_size: 1
gradient_accumulation_steps: 16
report_to: wandb
